- name: Download RustDesk Installer
  run: Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk.exe" -OutFile "$env:TEMP\rustdesk.exe"

- name: Install RustDesk
  run: Start-Process -FilePath "$env:TEMP\rustdesk.exe" -ArgumentList "/S" -NoNewWindow -Wait

